<a href="https://colab.research.google.com/github/shunnnl/2023-AI-BASIC/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제1

In [3]:
# Q1.
import numpy as np
arr=np.arange(1,6)
np.sum(np.sqrt(arr))

8.382332347441762

In [4]:
# Q2.
arr2=np.array([np.sum(arr),np.mean(arr),np.min(arr),np.max(arr)])
arr2

array([15.,  3.,  1.,  5.])

In [5]:
# Q3.
arr2.shape

(4,)

In [11]:
arr3=arr2.reshape(4,1)
arr3

array([[15.],
       [ 3.],
       [ 1.],
       [ 5.]])

In [12]:
# Q4.
np.dot(arr2,arr3)

array([260.])

In [14]:
arr3.dot(arr2.reshape(1,4))

array([[225.,  45.,  15.,  75.],
       [ 45.,   9.,   3.,  15.],
       [ 15.,   3.,   1.,   5.],
       [ 75.,  15.,   5.,  25.]])

# 과제2

In [15]:
# Q5.
arr=np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [18]:
# Q6.
arr=arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
# Q7.
arr2=arr[:2,1:]
arr2

array([[2, 3, 4],
       [6, 7, 8]])

In [24]:
arr3=arr[1:2,:3]
arr3

array([[5, 6, 7]])

In [34]:
# Q8.
arr3=arr3.reshape(3,1)
arr3

array([[5],
       [6],
       [7]])

In [35]:
# Q9.
np.dot(arr2,arr3)

array([[ 56],
       [128]])

# 과제3

In [5]:
# Q10.
# np.random.randint(시작범위, 끝범위, 개수) : int형으로 시작범위이상, 끝범위 미만으로 원하는 개수의 배열 생성

import numpy as np
arr=np.random.randint(3,7,4)
arr

array([3, 6, 6, 4])

In [6]:
# Q11.
arr.reshape(2,2)

array([[3, 6],
       [6, 4]])

In [8]:
# Q12.
num=int(input('로또번호를 몇 개 생성할까요?'))
for i in range(num):
  arr=np.random.randint(1,47,6)
  print('{}.로또번호:{}'.format(i+1,np.sort(arr)))

로또번호를 몇 개 생성할까요?3
1.로또번호:[ 1  8 27 35 41 46]
2.로또번호:[ 3 13 18 24 29 41]
3.로또번호:[ 2  7 14 14 38 40]


In [9]:
# Q13.
today=np.array([9,12,17,21,40,42])

num=int(input('로또번호를 몇 개 생성할까요?'))
for i in range(num):
  arr=np.random.randint(1,47,6)
  print('{}.로또번호:{}'.format(i+1,np.sort(arr)))
  if np.sum(arr)>np.sum(today):
    print('이벤트 당첨, 오늘의 로또번호 합= {},당첨된 로도번호 합={}'.format(np.sum(today),np.sum(arr)))
  

로또번호를 몇 개 생성할까요?3
1.로또번호:[ 8 27 33 41 42 43]
이벤트 당첨, 오늘의 로또번호 합= 141,당첨된 로도번호 합=194
2.로또번호:[ 3  5 22 28 32 46]
3.로또번호:[11 18 34 35 37 39]
이벤트 당첨, 오늘의 로또번호 합= 141,당첨된 로도번호 합=174


# 과제4

In [16]:
# Q14. 불리언 인덱스 활용
# True, False로만 이루어진 것에서도 그 값에 대응되는 것만 불러올 수 있음.
answer=np.array([3,2,1,4,4,3,4,4,3,3])
for i in range(10):
  arr=np.random.randint(1,6,10)
  check=np.array(answer==arr)
  print('{}.채점결과:{}, 점수:{}'.format(i+1,check,np.sum(check)))

1.채점결과:[ True False False False False False  True False False False], 점수:2
2.채점결과:[False False False False False  True False False False False], 점수:1
3.채점결과:[ True  True False False False False False  True False False], 점수:3
4.채점결과:[ True False False False False False False False False False], 점수:1
5.채점결과:[False False False False False  True  True False False False], 점수:2
6.채점결과:[False False False False False False False False False False], 점수:0
7.채점결과:[ True False False False False  True False False False  True], 점수:3
8.채점결과:[ True False False  True False  True  True False False False], 점수:4
9.채점결과:[False False False False False False False False  True False], 점수:1
10.채점결과:[False  True  True False False False  True False False False], 점수:3
