<a href="https://colab.research.google.com/github/shunnnl/2023-AI-BASIC/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.1.2 배열 만들기
## ndarray

*   메모리를 효율적으로 사용해 연산속도 빠름
*   벡터 산술연산 기능 제공
*   브로드캐스팅 기능 제공
*   반복문 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공



In [4]:
# numpy 사용
# np.array(list)
import numpy as np
list1=[1,2,3]
arr1=np.array(list1)
arr1

array([1, 2, 3])

In [5]:
# arr.tolist() : ndarray를 list로 반환
arr1.tolist()

[1, 2, 3]

In [6]:
# np.zeros(개수) : 0으로 채워진 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# np.ones(개수) : 1로 채워진 배열 생성
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
# np.empty(개수) : 쓰레기값으로 채워진 배열 생성
np.empty(9)

array([2.07350182e-316, 0.00000000e+000, 4.52176622e+217, 1.13469604e-153,
       4.57863245e+257, 1.23769929e+224, 2.52323784e+180, 1.15313936e+214,
       5.53353523e-322])

In [12]:
# np.arange() : 수의 순차적인 증감 이용하여 배열 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,22,2)

array([10, 12, 14, 16, 18, 20])

In [20]:
# np.random.rand() : 다양한 종류의 확률분포로부터 랜덤값을 생성 / 다차원 배열 생성시 () 필요없음!!!
np.random.rand(2,3)

array([[0.78057098, 0.52462241, 0.77880952],
       [0.69317014, 0.40903342, 0.73584354]])

In [25]:
# np.reshape()
arr2=np.arange(16)
arr2.reshape(4,4)
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [26]:
# arr.shape : 배열의 형태 확인
arr=np.arange(16)
arr.shape

(16,)

In [27]:
# arr.dtype : 배열의 데이터타입 확인
arr.dtype

dtype('int64')

In [28]:
# arr.astype() : 배열의 데이터타입 변경
arr.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [29]:
# np.string_ : 문자열 type
arr.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10',
       b'11', b'12', b'13', b'14', b'15'], dtype='|S21')

In [33]:
# arr.ndim : 배열의 차원
arr.ndim

1

In [36]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([[1,2,3],[4,5,6]],dtype=np.float32)
arr1.dtype,arr2.dtype

(dtype('float64'), dtype('float32'))

# 3.1.3 선택
## 기본 인덱스

In [40]:
import numpy as np
arr=np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
arr[-1]

15

In [42]:
arr[5:8]

array([5, 6, 7])

In [44]:
arr[10]=100
arr[6:8]=[76,77]
arr

array([  0,   1,   2,   3,   4,   5,  76,  77,   8,   9, 100,  11,  12,
        13,  14,  15])

In [46]:
arr2=np.arange(16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
arr2[1]

array([4, 5, 6, 7])

In [50]:
arr2[1,2]=100
arr2

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [53]:
arr2[:3]

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7],
       [  8,   9,  10,  11]])

In [55]:
arr2[:2,2:]

array([[  2,   3],
       [100,   7]])

## 불리언 인덱스

In [62]:
scores=[80,90,70,65,85,95,90,80,75,80]
score_arr=np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [63]:
score_arr>=90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [64]:
score_arr[score_arr>=90]=999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [67]:
colors=np.array(['red','blue','green','yellow','red','red'])
data=np.random.rand(6,4)
data

array([[0.76352404, 0.94520985, 0.45214329, 0.9268448 ],
       [0.16572794, 0.21990688, 0.77690963, 0.80358333],
       [0.690653  , 0.17819777, 0.11450953, 0.8951733 ],
       [0.34110996, 0.65119753, 0.10283454, 0.56170398],
       [0.1231797 , 0.56041804, 0.94648014, 0.2031165 ],
       [0.6305246 , 0.90698232, 0.14682772, 0.55880663]])

In [68]:
colors=='red'

array([ True, False, False, False,  True,  True])

In [69]:
data[colors=='red']

array([[0.76352404, 0.94520985, 0.45214329, 0.9268448 ],
       [0.1231797 , 0.56041804, 0.94648014, 0.2031165 ],
       [0.6305246 , 0.90698232, 0.14682772, 0.55880663]])

In [70]:
data[colors=='red',2:]

array([[0.45214329, 0.9268448 ],
       [0.94648014, 0.2031165 ],
       [0.14682772, 0.55880663]])

In [71]:
data[colors=='red',3]

array([0.9268448 , 0.2031165 , 0.55880663])

In [73]:
data[(colors=='yellow')|(colors=="blue")]=0
data

array([[0.76352404, 0.94520985, 0.45214329, 0.9268448 ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.690653  , 0.17819777, 0.11450953, 0.8951733 ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.1231797 , 0.56041804, 0.94648014, 0.2031165 ],
       [0.6305246 , 0.90698232, 0.14682772, 0.55880663]])

## (참고) 팬시 색인


*   fanct indexing
*   정수 리스트를 인덱스로 사용하는 방식



In [81]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [83]:
arr[[2,6]]

array([[ 8,  9, 10, 11],
       [24, 25, 26, 27]])

In [84]:
arr[[2,6],[1,3]]

array([ 9, 27])

In [85]:
# arr.take(index) : index에 있는 값을 반환
arr=np.arange(10)
index=[5,3,2,6]
arr.take(index)

array([5, 3, 2, 6])

In [86]:
# arr.put(index,value) : index에 있는 값을 value로 치환
arr.put(index,100)
arr

array([  0,   1, 100, 100,   4, 100, 100,   7,   8,   9])

In [87]:
arr.put(index,[50,51,52,53])
arr

array([ 0,  1, 52, 51,  4, 50, 53,  7,  8,  9])

# 3.1.4 연산
## 기본 사칙 연산


*   '+' : list와 array를 비교했을 때, array는 값을 더해주는 것이고 list는 자료형을 이어나가는 용도
*   '*' : list와 array를 비교했을 때, array는 값을 곱해주는 것이도, list는 같은 자료형을 반복하여 이어나가는 용도



In [88]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [89]:
arr+2

array([3, 4, 5, 6])

In [90]:
arr*2

array([2, 4, 6, 8])

In [92]:
list=[1,2,3,4]
list

[1, 2, 3, 4]

In [93]:
list*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [94]:
arr1=np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [95]:
arr1+arr

array([ 6,  8, 10, 12])

In [96]:
list1=[5,6,7,8]
list1+list1

[5, 6, 7, 8, 5, 6, 7, 8]

## (참고) 브로드캐스팅


*  shape이 다른 다차원배열 또는 스칼라 값 사이에서 연산이 가능



In [97]:
np.arange(3)+5

array([5, 6, 7])

In [98]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [101]:
np.arange(3).reshape(3,1)+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## 주요 산술 연산 함수
### 유니버셜 함수(ufunc)


*   ndarray에 있는 원소들 각각에 연산을 수행하여 결과를 반환
*   연산을 빠르게 수행할 수 있음



In [102]:
# np.square(arr) : 제곱
np.square(arr)

array([ 1,  4,  9, 16])

In [104]:
# np.sqrt(arr) : 루트
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [105]:
# np.exp(arr) : 지수승(e^x)
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [106]:
# np.log(arr) : log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [107]:
# np.add(배열1,배열2) : 더하기
np.add(arr,arr1)

array([ 6,  8, 10, 12])

In [108]:
# np.sum(arr) : 합계
np.sum(arr)

10

In [110]:
# np.cumsum(arr) : 누적합
np.cumsum(arr)

array([ 1,  3,  6, 10])

In [111]:
# np.mean(arr) : 평균
np.mean(arr)

2.5

In [112]:
# (참고)axis를 인자로 받아 차원에 따른 연산 수행 가능
# axis=0 : 세로끼리
# axis=1 : 가로끼리
arr_multi=np.arange(16).reshape(4,4)
print(arr_multi)
print('------------------------')
print('mean of axis 0:',arr_multi.mean(axis=0))
print('mean of axis 1:',arr_multi.mean(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------------------
mean of axis 0: [6. 7. 8. 9.]
mean of axis 1: [ 1.5  5.5  9.5 13.5]


In [113]:
# np.var(arr) : 편차
np.var(arr)

1.25

In [114]:
# np.std(arr) : 표준편차
np.std(arr)

1.118033988749895

In [116]:
# np.min(arr) : 최소값
np.min(arr)

1

In [117]:
# np.max(arr) : 최대값
np.max(arr)

4

In [118]:
# np.argmin(arr) : 최소값의 인덱스
np.argmin(arr)

0

In [119]:
# np.argmax(arr) : 최대값의 인덱스
np.argmax(arr)

3

In [120]:
# arr1.dot(arr2)
# np.dot(arr1,arr2) : 행렬곱

x=np.arange(6).reshape(2,3)
y=np.arange(6).reshape(3,2)
print('x \n',x)
print('\ny \n',y)

print('\nx.dot(y) \n',x.dot(y))
print('\nnp.dot(x,y) \n',np.dot(x,y))

x 
 [[0 1 2]
 [3 4 5]]

y 
 [[0 1]
 [2 3]
 [4 5]]

x.dot(y) 
 [[10 13]
 [28 40]]

np.dot(x,y) 
 [[10 13]
 [28 40]]


## (참고) 기타 연산

In [121]:
# np.where(조건,true일 때 실행, false일 때 실행) : 조건절
arr=np.arange(10).reshape(2,5)

# arr>5일 때, true인 부분에 10을 반환하고 false인 부분에 0을 반환
np.where(arr>5,10,0)

array([[ 0,  0,  0,  0,  0],
       [ 0, 10, 10, 10, 10]])

In [123]:
# np.sort() : 정렬
arr=np.random.rand(9).reshape(3,3)
print('정렬 이전:',arr)

arr.sort()
print('정렬 결과:',arr)

정렬 이전: [[0.83773824 0.76010918 0.8892843 ]
 [0.3854417  0.15923277 0.52045509]
 [0.01886832 0.71867855 0.59917736]]
정렬 결과: [[0.76010918 0.83773824 0.8892843 ]
 [0.15923277 0.3854417  0.52045509]
 [0.01886832 0.59917736 0.71867855]]


In [125]:
arr=np.random.rand(100)
print(arr)
arr.sort()

quantile_1=arr[int(0.25*len(arr))]
quantile_4=arr[int(0.75*len(arr))]

print('\n\n25%:',quantile_1, '75%:',quantile_4)

[0.31033906 0.86915151 0.63375569 0.22199439 0.49316717 0.960607
 0.76293442 0.14872804 0.18653662 0.4943311  0.18859511 0.4420535
 0.91953705 0.92237939 0.29908503 0.39339948 0.50242072 0.42245652
 0.93037741 0.98636157 0.02954888 0.13136616 0.4637572  0.89583439
 0.44766274 0.93820559 0.58329663 0.33106081 0.33230512 0.03783898
 0.82845527 0.3476778  0.42603965 0.08507467 0.19742163 0.1611566
 0.62513391 0.61193263 0.62684075 0.29219887 0.38929832 0.12579319
 0.36777425 0.46134412 0.91160808 0.19566047 0.84520705 0.78681071
 0.73800077 0.29862998 0.86874672 0.71794158 0.81262517 0.02640753
 0.54132332 0.38691835 0.79246338 0.43265173 0.11780344 0.11038607
 0.51491826 0.19155011 0.9099107  0.32849304 0.14133712 0.4342864
 0.75690559 0.38496179 0.44917665 0.80037346 0.44291573 0.78057556
 0.38155683 0.39193311 0.55791734 0.66965374 0.17522141 0.35352709
 0.49797145 0.45929314 0.93295839 0.41953503 0.16139456 0.48523068
 0.01472717 0.74607922 0.80307638 0.57392912 0.21277974 0.43071408


# 3.1.5 변형

In [126]:
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
# arr.transpose() : row와 col을 서로 교체 = arr.T
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [128]:
# arr.T : row와 col을 서로 교체
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [130]:
arr3d=np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [132]:
# arr3d.transpose(2,1,0)과 동일
arr3d.transpose()

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [134]:
arr3d.transpose(1,0,2)

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

In [141]:
# 행렬의 내적을 구할 때, 축의 전치를 활용
arr=np.random.rand(3,6)
np.dot(arr,arr.T)

array([[1.11093317, 1.3135727 , 1.42394491],
       [1.3135727 , 2.53574031, 2.00611258],
       [1.42394491, 2.00611258, 2.09248107]])

In [138]:
# newaxis : 새로운 축 추가
arr=np.zeros((2,2))
arr3d=arr[:,np.newaxis,:]
arr3d.shape

array([[[0., 0.]],

       [[0., 0.]]])

# 3.1.6 저장

*   ndarray를 바이너리 형식으로 디스크에 저장할 수 있음
*   대용량 데이터의 경우 읽고 쓰는데 시간을 줄일 수 있음



In [143]:
# np.save(저장하고자 하는 이름, arr) : arr을 저장하고자 하는 이름으로 디스크에 저장
# np.load(저장된 이름) : 변수에 디스크에 저장된 이름 찾아 담기
arr=np.arange(10).reshape(2,5)
np.save('array',arr)
load_arr=np.load('array.npy')
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [144]:
# np.savez(저장하고자 하는 이름, 인자1=arr1, 인자2=arr2) : 여러 배열을 압축된 형식으로 저장하고, 저장하려는 배열을 키워드 인자 형태로 전달
arr1=np.arange(10).reshape(2,5)
arr2=np.arange(10)
np.savez('array.npz',a=arr1,b=arr2)
arrs=np.load('array.npz')
arrs

In [145]:
arrs['a']

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [146]:
arrs['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arrs.close()